Выполнены задачи #2 раздела задачника
js-tasks-ru/js-20200928_stepanenkosg pull request #3
Opened 2020-10-04 09:35 UTC by stepanenkostas87

Выполнены задачи из раздела задачника Основы JS. Примитивные типы данных

2020-10-04 09:42 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-04 14:58 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const result = arr.slice().sort((a, b) => a.localeCompare(b, ['ru', 'en'], {caseFirst: 'upper'}));
более современный и компактный способ скопировать массив:
```
const arrCopy = [...arr];
```

2020-10-04 14:58 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  if (param === 'desc') return result.reverse();
в этом решении есть проблема - данные всегда сортируются по `asc` и только после этого происходит проверка `param === 'desc'` и в случае если она ложная, происходит `sorted.reverse()`

Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2020-10-04 15:00 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    if (!fields.includes(key)) delete result[key];
использование оператора `delete` крайне нежелательно на практике, более подробне поговорим об этом на занятии.
Подумайте как решить задачу без использования `delete`

2020-10-04 15:00 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    if (fields.includes(key)) delete result[key];
использование оператора `delete` крайне нежелательно на практике, более подробне поговорим об этом на занятии.
Подумайте как решить задачу без использования `delete`

2020-10-04 15:00 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-10-05 06:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-06 13:40 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let orient = 1;
попробуйте избавиться от `let`

2020-10-06 13:40 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  const result={}
good 👍

2020-10-06 13:40 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  for (let key of Object.keys(obj)) {
good 👍

2020-10-06 13:40 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-10-06 18:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-07 09:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-07 18:29 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    for (const key of path.split('.')) {
не стоит выполнять `path.split('.')` в цикле, так как эта операцию будет выполняться на каждую итерацию. Стоит выполнить `path.split('.')` только один раз. Подумайте где это лучше сделать

2020-10-07 18:29 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  if (obj === undefined) return undefined;
просто `return` мы не возвращаем `undefined` в явном виде

2020-10-07 18:29 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  if (size === undefined) return string;
решение принимается, обратите внимание на разбор данной задачи на занятии

2020-10-07 18:30 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return Array.from(new Set(arr));
good 👍 
подумайте в чем преимущества `Array.from` по сравнению с решением с использованием спред синтаксиса:
```
return [...new Set(arr)];
```

2020-10-07 18:31 UTC, dosandk requested changes
решения принимаются за исключением createGetter - необходимо поправить

2020-10-08 07:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-09 19:54 UTC, dosandk approved these changes

2020-10-09 19:55 UTC, merged